### ISSUE TITLE
Add custom attribute "assignedGroups" to Tasks

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/processmaker-bpmn-moddle#6]
Add a custom attribute **assignedGroups** to the Task definition.

 `<xsd:attribute name="assignedGroups" type="xsd:string"/>` 

Required by: [Assign Task to Group](https://github.com/ProcessMaker/bpm/issues/1157)

**Comment by nolanpro** [comment]
In this repo its just for fixtures, but should get added. I think `resources/processmaker.json` is the only file in this repo that needs to get modified

**Comment by caleeli** [comment]
Solve by #7
